config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

CodeTriage::Application.routes.draw do
  sitemap_url = File.join("https://#{ENV['BUCKETEER_BUCKET_NAME']}.s3.amazonaws.com/", "sitemaps", "sitemap.xml.gz")
  get 'sitemap.xml.gz', to: redirect(sitemap_url)

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :doc_methods, only: [:show]

  resources :university, only: [:show, :index]
  get 'example_app' => 'university#show', id: 'example_app'
  get 'reproduction' => 'university#show', id: 'reproduction'
  get 'repro' => 'university#show', id: 'reproduction'
  get 'squash' => 'university#show', id: 'squash'
  get 'rebase' => 'university#show', id: 'rebase'

  devise_for :users, skip: [:registration],
                     :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  as :user do
    get   'users/edit' => 'users#edit',   as: :edit_user_registration
    patch 'users'      => 'users#update', as: :user_registration
  end

  root to: "pages#index"

  get 'what'    => "pages#what"
  get 'privacy' => "pages#privacy"
  get 'support' => 'pages#support'

  namespace :users do
    resources :after_signup, only: [:show, :update]
  end

  resources   :users, only: [:show, :edit, :update, :destroy]
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments, only: [:create]

  get "/issue_assignments/:id/users/:user_id/click",  to: "issue_assignments#click_issue_redirect", as: :issue_click
  get "/doc_methods/:id/users/:user_id/click",        to: "doc_methods#click_method_redirect",      as: :doc_method_click
  get "/doc_methods/:id/users/:user_id/source_click", to: "doc_methods#click_source_redirect",      as: :doc_source_click

  resources :repo_subscriptions, only: [:create, :destroy, :update]

  get 'mail_view', to: redirect('rails/mailers')

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: [:index, :new, :create] do
      collection do
        get :list
      end
    end

    scope '*full_name' do
      constraints full_name: /[-_a-zA-Z0-9]+\/[-_\.a-zA-Z0-9]+/ do
        get   '/badges/:badge_type(.:format)', to: 'badges#show', as: 'badge'
        get   'info(.:format)',           to: 'api_info#show'

        get   '/',              to: 'repos#show',        as: 'repo'
        patch '/',              to: 'repos#update',      as: nil
        get   '/edit',          to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers',   to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/models/github_fetcher/user.rb
# frozen_string_literal: true

module GithubFetcher
  class User < Resource
    def initialize(options)
      @api_path = '/user'
      super
    end

    def valid?
      begin
        GitHubBub.valid_token?(@options[:token])
      rescue GitHubBub::RequestError
        false
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules (but not :registerable). Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable,
  # :omniauthable, and :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :omniauthable

  validates_uniqueness_of :email,    allow_blank: true, if: :email_changed?
  validates_length_of     :password, within: 8..128, allow_blank: true
  validates :github, presence: true, uniqueness: true
  validates :email_frequency, inclusion: { in: EmailRateLimit::USER_STATES.map(&:to_s) + [nil], message: "Not a valid frequency, pick from #{EmailRateLimit::USER_STATES}" }

  # Setup accessible (or protected) attributes for your model

  has_many :repo_subscriptions, dependent: :destroy
  has_many :repo_assignments, through: :repo_subscriptions
  has_many :repos, through: :repo_subscriptions

  has_many :issue_assignments, through: :repo_subscriptions
  has_many :issues,            through: :issue_assignments

  scope :public_profile, -> { where.not(users: { private: true }) }

  alias_attribute :token, :github_access_token

  delegate :for, to: :repo_subscriptions, prefix: true
  before_save :set_default_last_clicked_at

  def self.with_repo_subscriptions
    left_outer_joins(:repo_subscriptions)
      .where("repo_id is not null")
      .distinct
  end

  # users that are not subscribed to any repos
  def self.inactive
    joins("LEFT OUTER JOIN repo_subscriptions on users.id = repo_subscriptions.user_id").where("repo_subscriptions.user_id is null")
  end

  # We record when an email is sent out, which includes
  # the current day's email. When raw_emails_since_click = 1
  # then there have been zero emails missed.
  def emails_missed_since_click
    return 0 if raw_emails_since_click <= 0
    raw_emails_since_click - 1
  end

  # The `raw_streak_count` is the value stored in the
  # DB. This value should be updated when a user clicks on an
  # email.
  #
  # The `emails_missed_since_click` is updated every time
  # we send an email.
  #
  # The streak count is the prior saved streak minus the number
  # of emails the user has not clicked.
  def effective_streak_count
    value = raw_streak_count - emails_missed_since_click
    return 0 if value < 0
    return value
  end

  def record_click!(save: true)
    return if raw_emails_since_click.zero?

    self.raw_streak_count       = effective_streak_count + 1
    self.raw_emails_since_click = 0
    self.save! if save
  end

  def subscribe_docs!
    subscriptions = self.repo_subscriptions.order(Arel.sql('RANDOM()')).load
    DocMailerMaker.new(self, subscriptions) { |sub| sub.ready_for_next? }.deliver_later
  end

  def set_default_last_clicked_at
    self.last_clicked_at ||= Time.now
  end

  def own_repos_json(per_page = 100)
    repos_fetcher(GithubFetcher::Repos::OWNED, token: token, per_page: per_page.to_s).as_json
  end

  def starred_repos_json
    repos_fetcher(GithubFetcher::Repos::STARRED, token: token).as_json
  end

  def subscribed_repos_json
    repos_fetcher(GithubFetcher::Repos::SUBSCRIBED, token: token).as_json
  end

  def fetcher
    @fetcher ||= GithubFetcher::User.new(token: token)
  end

  def repos_fetcher(kind, options = {})
    GithubFetcher::Repos.new({ token: token, kind: kind }.merge(options))
  end

  def auth_is_valid?
    fetcher.valid?
  end

  @@max_id = nil
  def self.random
    @@max_id = self.maximum(:id) if @@max_id.nil?

    where("id >= ?", Random.new.rand(1..@@max_id))
  end

  def default_avatar_url
    "http://gravatar.com/avatar/default"
  end

  def account_delete_token
    if self[:account_delete_token].blank?
      self.account_delete_token = SecureRandom.hex(64)
      update_attribute(:account_delete_token, account_delete_token) unless new_record?
    end

    self[:account_delete_token]
  end

  def enqueue_inactive_email
    background_inactive_email(self.id)
  end

  def able_to_edit_repo?(repo)
    repo.user_name == github.downcase
  end

  def public?
    !private
  end

  def not_yet_subscribed_to?(repo)
    !subscribed_to?(repo)
  end

  def subscribed_to?(repo)
    sub_from_repo(repo).present?
  end

  def sub_from_repo(repo)
    self.repo_subscriptions.find_by(repo_id: repo.id)
  end

  def github_json
    fetcher.json
  end

  def fetch_avatar_url
    github_json["avatar_url"]
  end

  def set_avatar_url!
    self.avatar_url = self.fetch_avatar_url || default_avatar_url
    self.save!
  end

  def github_url
    "https://github.com/#{github}"
  end

  def valid_email?
    ValidateEmail.valid?(email)
  end

  def days_since_last_clicked
    return 0 if last_clicked_at.blank?
    (
      (Time.now - last_clicked_at) / 1.day
    ).ceil # only want whole days
  end

  def days_since_last_email
    last_sent_at = repo_subscriptions.where("last_sent_at is not null").order(:last_sent_at).first.try(:last_sent_at)
    last_sent_at ||= self.created_at
    (
      (Time.now - last_sent_at) / 1.day
    ).ceil # only want whole days
  end

  def favorite_language?(language)
    favorite_languages.include? language if favorite_languages
  end

  def has_favorite_languages?
    favorite_languages && !favorite_languages.empty?
  end

  def issue_assignments_to_deliver(assign: true)
    prior_assignments = issue_assignments.where(delivered: false).limit(daily_issue_limit)
    return prior_assignments unless prior_assignments.blank?

    issue_assigner.assign! if assign
    issue_assignments.where(delivered: false).limit(daily_issue_limit)
  end

  private

  def issue_assigner
    @issue_assigner ||= IssueAssigner.new(self, repo_subscriptions)
  end
end

app/controllers/users/after_signup_controller.rb
# frozen_string_literal: true

class Users::AfterSignupController < ApplicationController
  include Wicked::Wizard

  before_action :authenticate_user!

  steps :set_privacy

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.update(user_params)
    render_wizard @user
  end

  private

  def user_params
    params.require(:user).permit(
      :private,
      :email,
      :password,
      :password_confirmation,
      :remember_me,
      :zip,
      :phone_number,
      :twitter,
      :github,
      :github_access_token,
      :avatar_url,
      :name,
      :favorite_languages,
      :daily_issue_limit
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = GitHubAuthenticator.authenticate(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = if @user.valid_email?
                         I18n.t "devise.omniauth_callbacks.success", kind: "GitHub"
                       else
                         I18n.t "devise.omniauth_callbacks.bad_email_success", kind: "GitHub"
                       end

      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"].delete("extra")
      flash[:error]  = no_email_error if request.env["omniauth.auth"].info.email.blank?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.failure",
                              kind: "GitHub", reason: "Invalid credentials" if flash[:error].blank?
      redirect_to root_path
    end
  end

  private

  def no_email_error
    msg =  "You need a public email address on GitHub to sign up you can add"
    msg << " an email, sign up for triage, then remove it from GitHub:<hr />"
    msg << "<a href='https://github.com/settings/profile'>GitHub Profile</a>"
    msg.html_safe
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    if @user.private?
      redirect_to root_path unless current_user && @user == current_user
    end
  end

  def edit
    @user = current_user
  end

  def update
    begin
      uparams = user_params
    rescue ActionController::ParameterMissing
      uparams = { favorite_languages: [] }
    end

    @user = current_user
    if @user.update(uparams)
      redirect_to @user, flash: { success: 'User successfully updated' }
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_url, notice: "Successfully removed your user account"
  end

  def token_delete
    @user = User.find_by(account_delete_token: params[:account_delete_token])

    if @user.nil?
      redirect_to root_url, notice: "Account could not be found. You may have already deleted it, or your GitHub username may have changed."
    else
      @lonely_repos = @user.repos.where(subscribers_count: 0)
    end
  end

  def token_destroy
    @user = User.find_by!(account_delete_token: params[:account_delete_token])
    @user.destroy
    redirect_to root_url, notice: "Successfully removed your user account"
  end

  private

  def user_params
    params.require(:user).permit(
      :private,
      :email,
      :password,
      :password_confirmation,
      :remember_me,
      :zip,
      :phone_number,
      :twitter,
      :github,
      :github_access_token,
      :avatar_url,
      :name,
      :daily_issue_limit,
      :email_frequency,
      :email_time_of_day,
      :skip_issues_with_pr,
      favorite_languages: []
    )
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def available_times_of_day
    (0...24).map { |hour| Time.utc(2000, 1, 1, hour, 00, 0) }
  end
end

app/views/users/_form.html.slim
.clearfix
  = f.label :email, t("activerecord.attributes.user.email", default: "Email"), class: "label label-info"
  .controls
    .input-prepend
      span.add-on
        i.icon-envelope
      = f.text_field :email, class: 'text_field'
  = f.label :email_frequency, t("activerecord.attributes.user.email_frequency", default: "Email Frequency"), class: "label label-info"
  .controls
    .input-preprend
      span.add-on
        i.icon-envelope
      = f.select :email_frequency, options_for_select( EmailRateLimit::USER_STATES_HASH.map {|key, name| [ name, key ] }, f.object.email_frequency), class: 'select'
      p When you're busy we try to send you fewer emails, if that's not good enough set your desired frequency here. For example if you set "twice a week" you won't receive more than 2 emails a week.
      p How often should you get emails? It depends on your goals:
      ul.bullets
        li <strong>Daily:</strong><i> "I want to ramp up as fast as possible, I'm working towards becoming a committer ASAP."</i>
        li <strong>Twice a week:</strong></i> "Being a committer is still in my sights, but it doesn't need to be tomorrow."</i>
        li <strong>Once a week:</strong><i> "I might be a committer one day, but for now I only want to help out here and there."</i>
        li <strong>Once a month:</strong> <i>"I want to see casually what's going on and I want to help a tiny bit."</i>
      br
      p The most important thing is consistency. No matter the frequency you can commit to, keep clicking on issues, keep learning, and you'll get there!

  = f.label :email_time_of_day, t("activerecord.attributes.user.email_time_of_day", default: "Email time of day"), class: "label label-info"
  .controls
    .input-preprend
      span.add-on
        i.icon-envelope
      = f.select :email_time_of_day,
          options_for_select(available_times_of_day.map { |time| [time.to_formatted_s(:time_only_with_zone), time.to_formatted_s(:iso8601)] }, f.object.email_time_of_day&.to_formatted_s(:iso8601)),
          class: 'select'

  = f.label :daily_issue_limit, t("activerecord.attributes.user.daily_issue_limit", default: "Max # of issues you want to receive per day"), class: "label label-info"
  .input
    = f.number_field :daily_issue_limit, class: 'number_field', min: 0
    p If you're getting too many issues, limit the maximum number you want to get in your inbox at one time. To disable submit an empty value.

  = f.check_box :skip_issues_with_pr, class: 'checkbox'
  => f.label :skip_issues_with_pr, t("activerecord.attributes.user.skip_issues_with_pr", default: "Skip Pull requests"), class: "label label-info"
  p By default we send you a combination of issues and pull request, check this box to only get Issues.

.form-actions
  => button_tag "Save", class: "button full-width-action"

app/views/users/edit.html.slim
.subpage-content-wrapper
  section.subpage-content-header
    h1.subpage-primary-title
      | Edit 
      = @user.github

  section.user-settings.content-section
    = form_for @user, url: user_path(@user), method: :patch, html: { class: "edit_user", id: "edit_user" } do |f|
      = render partial: "form", locals: {f: f}

app/views/users/show.html.slim
- if current_user.blank?
  section.user-logged-out
    h1= link_to 'Login to view your account', user_github_omniauth_authorize_path, method: :post

- if current_user && current_user == @user
  .subpage-content-wrapper
    section.subpage-content-header
      h1.subpage-primary-title= @user.github
      h2.subpage-secondary-title.user-email= @user.email

      .subpage-header-actions
        = link_to 'Delete Account'.html_safe, token_delete_user_url(@user.account_delete_token)
        = link_to 'Edit Account'.html_safe, edit_user_path(@user), class: 'header-primary-action'

    section.user-settings.content-section
      h2.content-section-title Settings

      ul.slats-list
        li.slats-item
          .slats-hgroup
            h3 Is your account shown to everyone:

          .slats-action
            p
              - if @user.public?
                | Public,
                = link_to "Go private", user_registration_path(user: {private: true}), method: :patch
              - else
                | Private,
                = link_to "Go public", user_registration_path(user: {private: false}), method: :patch
        li.slats-item
          .slats-hgroup
            h3.slats-title Email frequency:
          .slats-action
            p= @user.email_frequency.presence || 'not set'

        li.slats-item
          .slats-hgroup
            h3.slats-title Email time of day:
          .slats-action
            p= (@user.email_time_of_day && local_time(@user.email_time_of_day, '%H:%M %Z')) || 'not set'

        li.slats-item
          .slats-hgroup
            h3.slats-title Max number of issues you want to receive per day:
          .slats-action
            p= @user.daily_issue_limit.presence || 'not set'

        li.slats-item
          .slats-hgroup
            h3.slats-title Skip Issues with Pull Requests:
          .slats-action
            p= @user.skip_issues_with_pr

    section.user-favorite-langs.content-section
      h2.content-section-title Select your favorite languages:
      = form_for @user do |f|
        ul.all-languages-list
          - Repo.all_languages.each do |language|
            li.language-item
              = f.check_box :favorite_languages, { multiple: true }, language, nil
              = f.label language, for: "user_favorite_languages_#{language.downcase}"
        p= button_tag "Save Favorite Languages", class: "button full-width-action"

app/views/users/token_delete.html.slim
section.subpage-content-wrapper.high
  header.subpage-content-header
    h1.subpage-primary-title Delete Account?
    p.subpage-secondary-title This cannot be undone.

  .repo-body
    - if @lonely_repos.present?
      section.help-triage.content-section
        | If you delete your account these CodeTriage repos will have no subscribers and will be removed as well.
        ul.bullets
          - @lonely_repos.each do |repo|
            li= link_to repo.full_name, repo_path(repo)

    section.help-triage.content-section
      | The only thing this app does is send emails. The only way to unsubscribe is account deletion. If you have feedback for the project, please
      = link_to " open up an issue on GitHub", "https://github.com/codetriage/codetriage/issues"
      | .

    section.help-triage.content-section
      = form_for @user, url: token_delete_user_path(@user.account_delete_token), method: :delete, html_options: { class: "form form-horizontal danger" } do |f|
        = link_to "Cancel", root_url, class: "button"
        | &nbsp;
        | &nbsp;
        = f.submit "💀 Delete My Account", class: "btn btn-danger", id: "destroy_user", data: { confirm: 'This cannot be undone, are you sure?' }