config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

CodeTriage::Application.routes.draw do
  sitemap_url = File.join("https://#{ENV['BUCKETEER_BUCKET_NAME']}.s3.amazonaws.com/", "sitemaps", "sitemap.xml.gz")
  get 'sitemap.xml.gz', to: redirect(sitemap_url)

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :doc_methods, only: [:show]

  resources :university, only: [:show, :index]
  get 'example_app' => 'university#show', id: 'example_app'
  get 'reproduction' => 'university#show', id: 'reproduction'
  get 'repro' => 'university#show', id: 'reproduction'
  get 'squash' => 'university#show', id: 'squash'
  get 'rebase' => 'university#show', id: 'rebase'

  devise_for :users, skip: [:registration],
                     :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  as :user do
    get   'users/edit' => 'users#edit',   as: :edit_user_registration
    patch 'users'      => 'users#update', as: :user_registration
  end

  root to: "pages#index"

  get 'what'    => "pages#what"
  get 'privacy' => "pages#privacy"
  get 'support' => 'pages#support'

  namespace :users do
    resources :after_signup, only: [:show, :update]
  end

  resources   :users, only: [:show, :edit, :update, :destroy]
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments, only: [:create]

  get "/issue_assignments/:id/users/:user_id/click",  to: "issue_assignments#click_issue_redirect", as: :issue_click
  get "/doc_methods/:id/users/:user_id/click",        to: "doc_methods#click_method_redirect",      as: :doc_method_click
  get "/doc_methods/:id/users/:user_id/source_click", to: "doc_methods#click_source_redirect",      as: :doc_source_click

  resources :repo_subscriptions, only: [:create, :destroy, :update]

  get 'mail_view', to: redirect('rails/mailers')

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: [:index, :new, :create] do
      collection do
        get :list
      end
    end

    scope '*full_name' do
      constraints full_name: /[-_a-zA-Z0-9]+\/[-_\.a-zA-Z0-9]+/ do
        get   '/badges/:badge_type(.:format)', to: 'badges#show', as: 'badge'
        get   'info(.:format)',           to: 'api_info#show'

        get   '/',              to: 'repos#show',        as: 'repo'
        patch '/',              to: 'repos#update',      as: nil
        get   '/edit',          to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers',   to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionView::Helpers::NumberHelper
  protect_from_forgery

  before_action do
    if current_user && current_user.admin?
      Rack::MiniProfiler.authorize_request
    end
  end

  before_action do
    if current_user
      Raven.user_context email: current_user.email, id: current_user.id, username: current_user.github
    end
  end

  def set_description(val)
    @meta_description = val
  end

  def set_title(val)
    @meta_title = val
  end

  def authenticate_user!
    redirect_to user_github_omniauth_authorize_path(origin: request.fullpath) unless user_signed_in?
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  WARNING_SVG = %Q{
<?xml version="1.0" encoding="UTF-8"?>
<svg width="16px" height="16px" class="issue-icon" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
<path d="m8 0c-4.418 0-8 3.582-8 8s3.582 8 8 8 8-3.582 8-8-3.582-8-8-8zm0 14c-3.309 0-6-2.692-6-6s2.691-6 6-6c3.307 0 6 2.692 6 6s-2.693 6-6 6z" clip-rule="evenodd" fill-rule="evenodd"/>
<path d="M8.5,3h-1C7.224,3,7,3.224,7,3.5v6C7,9.776,7.224,10,7.5,10h1 C8.776,10,9,9.776,9,9.5v-6C9,3.224,8.776,3,8.5,3z" clip-rule="evenodd" fill-rule="evenodd"/>
<path d="M8.5,11h-1C7.224,11,7,11.224,7,11.5v1C7,12.776,7.224,13,7.5,13h1 C8.776,13,9,12.776,9,12.5v-1C9,11.224,8.776,11,8.5,11z" clip-rule="evenodd" fill-rule="evenodd"/>
</svg>
}.html_safe

  STAR_SVG = %Q{
    <svg version="1.1" xmlns="//www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 16 16" class="star-icon">
      <polygon fill="white" stroke="white" stroke-width="2" points="8,3 12,13 3,7 13,7 4,13" />
    </svg>
  }.html_safe

  def flash_class(level)
    case level
    when :notice then 'info'
    when :error then 'error'
    when :alert then 'warning'
    end
  end

  def warning_svg
    WARNING_SVG
  end

  def star_svg
    STAR_SVG
  end
end

app/views/application/_down.html.slim
<svg version="1.1" width="16px" height="16px" viewBox="0 0 16 16" class="down-circle">
  <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M5.327,6h5.347c0.296,0,0.411,0.202,0.26,0.451l-2.658,4.362 c-0.151,0.249-0.398,0.249-0.55,0L5.066,6.451C4.915,6.202,5.031,6,5.327,6z"/>
  <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M8,0C3.582,0,0,3.582,0,8s3.582,8,8,8s8-3.582,8-8S12.418,0,8,0z M8,14 c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S11.309,14,8,14z"/>
</svg>

app/views/application/_flashes.html.slim
- [:notice, :error, :alert, :success].each do |level|
  - unless flash[level].blank?
    div class="alert flash-#{level}"
      = content_tag :p, flash[level]

app/views/application/_footer.html.slim
footer.application-footer
  hr.section-break
  = link_to "Submit a Repo", new_repo_path, class: 'button footer-action'

  h2.credit-title Sponsors
  section.credits
    a href="https://ter.li/pi16r5" class="credits-link"
      = image_tag "sponsors/scout.png", class: "credits-logo", alt: 'Scout logo (sponsors CodeTriage)'

  h2.credit-title Credits
  section.credits
    a href="https://www.schneems.com" class="credits-link"
      = image_tag "schneems.svg", class: "credits-logo", alt: 'Schneems logo (created CodeTriage)'
      | Created by Schneems

    a href="https://thoughtbot.com" class="credits-link"
      = image_tag "thoughtbot.svg", class: "credits-logo", alt: 'Thoughtbot logo (donated some visual designer time)'
      | Designed by thoughtbot

    a href="https://www.heroku.com" class="credits-link"
      = image_tag "heroku.svg", class: "credits-logo heroku-logo", alt: 'Heroku logo (app runs on the Heroku platform)'
      | Powered by Heroku

  p.housekeeping
    = link_to "What is CodeTriage?", what_path
    = link_to "Privacy Policy", privacy_path
    = link_to "Support", support_path
    = link_to "Fork us on GitHub", "https://github.com/codetriage/codetriage"

  p
    | &copy; CodeTriage &nbsp;
    = Time.now.year

app/views/application/_head.html.slim
head
  meta charset="utf-8"
  title
    = @meta_title ? "#{@meta_title} | CodeTriage" : "CodeTriage"

  meta name="viewport" content="width=device-width, initial-scale=1.0"
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all"

  = favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon'
  = favicon_link_tag 'favicon.ico', rel: 'icon', type: 'image/x-icon'

  <script src="//use.typekit.net/vyg4pus.js"></script>
  <script>try{Typekit.load({ async: true  });}catch(e){}</script>

  meta name="description" content="#{ @meta_description || 'The easiest way to get started contributing to open source projects.' }"

  = javascript_include_tag "application", async: true

  - if Rails.env.production?
    /! google analytics
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-102491943-1', 'auto');
      ga('send', 'pageview');

app/views/application/_nav.html.slim
noscript
  .alert.flash-error CodeTriage requires JavaScript, please enable it!

.top-bar-red
.top-bar-yellow
.top-bar-green
.top-bar-blue

nav.application-navigation
  ul.application-navigation-list
    - if user_signed_in?
      li.application-navigation-list-item= image_tag current_user.avatar_url, class: 'user-profile-image', alt: 'user avatar'
      li.application-navigation-list-item= link_to current_user.github, current_user
      li.application-navigation-list-item= link_to 'University', university_index_path
      li.application-navigation-list-item= link_to "Submit Repo", new_repo_path
      li.application-navigation-list-item= link_to "Sign Out", destroy_user_session_path, method: :delete
    - else
      li.application-navigation-list-item= link_to 'About', what_path
      li.application-navigation-list-item= link_to 'University', university_index_path
      li.application-navigation-list-item= link_to 'Log in', user_github_omniauth_authorize_path, method: :post
      li.application-navigation-list-item= link_to 'Sign Up', user_github_omniauth_authorize_path, method: :post

div.application-logo
  = link_to root_path
    span.application-logo-image
    span.hide-visually Code Triage Home